import "./globals.css";
import type { Metadata } from "next";
import HydrationWrapper from "@/lib/hydration";
import Toggle from "@/src/components/theme/toggle";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/src/components/theme/theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          enableSystem
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
        >
          <HydrationWrapper>
            <div className="fixed top-0 right-0 z-[9999]">
              <Toggle />
            </div>
          </HydrationWrapper>

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
