import "./globals.css";
import type { Metadata } from "next";
import Docked from "@/src/blocks/dock";
import HydrationWrapper from "@/lib/hydration";
import Toggle from "@/src/components/theme/toggle";
import { ThemeProvider } from "@/src/components/theme/theme";

export const metadata: Metadata = {
  title: "soikat-san",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <div className="max-w-[1920px] m-auto relative">
          <ThemeProvider
            enableSystem
            attribute="class"
            defaultTheme="system"
            disableTransitionOnChange
          >
            <HydrationWrapper>
              <div className="absolute top-2 right-4 z-[9999]">
                <Toggle />
              </div>
              <div className="fixed bottom-0 left-1/2 transform -translate-x-1/2 z-[9998] max-w-[1920px]">
                <Docked />
              </div>
              {children}
            </HydrationWrapper>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
